### ISSUE TITLE
Suggest checklist items by the event name

### ISSUE THREAD

**Issue by GevaOr** [PythonFreeCourse/calendar#120]
Forum post [HERE](https://forums.pythonic.guru/t/topic/8811).

- [ ] **Create tables in the DB:** 
- keywords.
- suggestions.
- keyword_suggestions (junction table).

- [ ] **Functionality:**
- Extract the type of event from the event name.
- Return all suggestions for the event type.

- [ ] **Frontend** - show a message in the checklist with suggestions.

- [ ] **Tests** - compare some known existing event type suggestions to the app's output.
